name: TypeScript - Test

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Test with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --production=false
    - run: yarn test:unit
      env:
        CI: true
